FROM amazoncorretto:8
WORKDIR C:/Repositorio/Portfolio/Backend/SpringBoot/
MAINTAINER portfolio_velazquez
COPY target/SpringBoot-0.0.1-SNAPSHOT.jar SpringBoot-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/SpringBoot-0.0.1-SNAPSHOT.jar"]